# Generated by Django 6.0.1 on 2026-01-13 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemcategory',
            options={'verbose_name': 'Item category', 'verbose_name_plural': 'Item categories'},
        ),
    ]
