# Generated by Django 6.0.1 on 2026-01-13 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderitem'),
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='When the buffet session expires', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='plans.plan'),
        ),
        migrations.AddField(
            model_name='order',
            name='started_at',
            field=models.DateTimeField(blank=True, help_text='When the buffet session started', null=True),
        ),
    ]
