# Generated by Django 6.0.1 on 2026-01-13 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_expires_at_order_plan_order_started_at'),
        ('plans', '0002_alter_itemcategory_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='plans.plan'),
        ),
    ]
